name: 'Setup wasmtime-py CI'
inputs:
  python-version:
    description: 'Version of Python to configure'
    required: false
    default: '3.x'
runs:
  using: "composite"
  steps:
  # Setup Python and the Python dependencies of this project
  - uses: actions/setup-python@v6
    with:
      python-version: ${{ inputs.python-version }}

  - name: Install uv
    uses: astral-sh/setup-uv@v7

  - name: Show python in-use
    shell: bash
    run: uv run python --version

  # Download precompiled wasmtime binaries for running the project
  - run: uv run ci/download-wasmtime.py
    shell: bash
