[package]
name = "wasi_snapshot_preview1"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
wasi = "0.11.0"
wit-bindgen = { workspace = true, default-features = false, features = ['macros'] }
