[package]
name = "bindgen"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.0.0"
publish = false
edition = "2021"

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
anyhow = "1.0"
heck = { version = "0.4", features = ["unicode"] }
wit-component = "0.4"
wit-parser = "0.4"
indexmap = "1.0"
wasmtime-environ = { version = "6.0.0", features = ['component-model'] }
wit-bindgen-guest-rust = { workspace = true, features = ['default'] }

[features]
cli = []

[[bin]]
name = "bootstrap"
required-features = ["cli"]

